//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Exchanges = new HashSet<Exchanges>();
            this.Notifications = new HashSet<Notifications>();
            this.Ratings = new HashSet<Ratings>();
        }
    
        public int BookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Genre { get; set; }
        public string Condition { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string BookPicture { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ICollection<Exchanges> Exchanges { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
    }
}
