//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchanges
    {
        public Exchanges()
        {
            this.Ratings = new HashSet<Ratings>();
        }
    
        public int ExchangeID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> RequestorID { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Status { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
    }
}
