//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookExchange.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineBookExchangeEntities : DbContext
    {
        public OnlineBookExchangeEntities()
            : base("name=OnlineBookExchangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Books> Books { get; set; }
        public DbSet<Exchanges> Exchanges { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Notifications> Notifications { get; set; }
        public DbSet<Ratings> Ratings { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<ReportedIssues> ReportedIssues { get; set; }
    }
}
