//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ratings
    {
        public int RatingID { get; set; }
        public Nullable<int> Exchange_id { get; set; }
        public Nullable<int> RaterID { get; set; }
        public string Rview { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> RateeID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ExchangePartnerRating { get; set; }
        public Nullable<int> BookConditionRating { get; set; }
    
        public virtual Exchanges Exchanges { get; set; }
        public virtual Users Users { get; set; }
        public virtual Books Books { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
