//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Books = new HashSet<Books>();
            this.Exchanges = new HashSet<Exchanges>();
            this.Exchanges1 = new HashSet<Exchanges>();
            this.Message = new HashSet<Message>();
            this.Message1 = new HashSet<Message>();
            this.Notifications = new HashSet<Notifications>();
            this.Ratings = new HashSet<Ratings>();
            this.ReportedIssues = new HashSet<ReportedIssues>();
            this.Ratings1 = new HashSet<Ratings>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ProfilePicture { get; set; }
    
        public virtual ICollection<Books> Books { get; set; }
        public virtual ICollection<Exchanges> Exchanges { get; set; }
        public virtual ICollection<Exchanges> Exchanges1 { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<Message> Message1 { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
        public virtual ICollection<ReportedIssues> ReportedIssues { get; set; }
        public virtual ICollection<Ratings> Ratings1 { get; set; }
    }
}
