//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBookExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVerifications
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CNICNumber { get; set; }
        public string CNICFrontImage { get; set; }
        public string CNICBackImage { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
